# Generated by Django 5.1.2 on 2024-11-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistify', '0002_dialog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='settings',
            field=models.JSONField(default={'audio': {'disabled': False, 'language': 'ru-RU', 'voiceNames': ['Google русский (ru-RU)']}, 'botBubble': {'showAvatar': True}, 'chatHistory': {'storageKey': 'conversations_summary'}, 'general': {'embedded': False}, 'header': {'avatar': '/logo.svg'}, 'tooltip': {'mode': 'CLOSE', 'text': 'Talk to me! 😊'}, 'voice': {'disabled': False, 'language': 'ru-RU'}}),
        ),
    ]
