# Generated by Django 5.1.2 on 2024-11-26 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistify', '0003_alter_dialog_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dialog', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
